management:
  endpoints:
    web:
      exposure:
        include: "*"

#spring:
#  data:
#    mongodb:
#      uri: mongodb://localhost:27017/webflux_demo

#local:
#  mongo:
#    port: 27017

#spring:
#  data:
#    mongodb:
#      port: 27017

#---
#spring:
#  profiles:
#    active: cloud
#  data:
#    mongodb:
#      uri: ${vcap.services.broker-db.credentials.uri:mongodb://localhost:27017/broker-db}
#      username: ${vcap.services.broker-db.credentials.username:}
#      password: ${vcap.services.broker-db.credentials.password:}